---
galaxy_info:
  author: Shoshana Makinen
  description: Installs Docker CE, containerd, and the Docker Compose CLI plugin, and adds users to the docker group

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
