namespace: vmutti
name: worchestation

version: 1.0.10

readme: README.md

authors:
- Joshua Makinen <makinj64@gmail.com>

description: your collection description

license:
- MIT
license_file: ''
tags: []

dependencies:
  vmutti.updates: '>=1.0.0'
  vmutti.virtualbox_guest: '>=1.0.0'
  vmutti.users: '>=1.0.0'
  vmutti.zsh: '>=1.0.0'
  vmutti.tmux: '>=1.0.0'
  vmutti.vim: '>=1.0.0'
  vmutti.xfce: '>=1.0.0'
  vmutti.fonts: '>=1.0.0'
  vmutti.background: '>=1.0.0'
  vmutti.chrome: '>=1.0.0'
  vmutti.alacritty: '>=1.0.0'
  vmutti.sublime: '>=1.0.0'
  vmutti.docker: '>=1.0.0'
  vmutti.gcloud: '>=1.0.0'
  vmutti.kubectl: '>=1.0.0'
  vmutti.golang: '>=1.0.0'
  vmutti.kind: '>=1.0.0'
  vmutti.autochrome: '>=1.0.0'
  vmutti.mitmproxy: '>=1.0.0'
  # vmutti.kali: '>=1.0.0'
  # vmutti.aws: '>=1.0.0'
  # vmutti.configs: '>=1.0.0'
  # vmutti.ethereum: '>=1.0.0'
  # vmutti.samba: '>=1.0.0'
  # vmutti.scoutsuite: '>=1.0.0'
  # vmutti.terraform: '>=1.0.0'
  # vmutti.packer: '>=1.0.0'
  # vmutti.vagrant: '>=1.0.0'
  # vmutti.vault: '>=1.0.0'
repository: https://github.com/vmutti/AnsibleCollections
issues: https://github.com/vmutti/AnsibleCollections/issues
build_ignore: []

