namespace: vmutti
name: worchestation

version: 1.0.10

readme: README.md

authors:
- Joshua Makinen <makinj64@gmail.com>

description: your collection description

license:
- MIT
license_file: ''
tags: []

dependencies:
  makinj.updates: '>=1.0.0'
  makinj.virtualbox_guest: '>=1.0.0'
  makinj.users: '>=1.0.0'
  makinj.zsh: '>=1.0.0'
  makinj.tmux: '>=1.0.0'
  makinj.vim: '>=1.0.0'
  makinj.xfce: '>=1.0.0'
  makinj.fonts: '>=1.0.0'
  makinj.background: '>=1.0.0'
  makinj.chrome: '>=1.0.0'
  makinj.alacritty: '>=1.0.0'
  makinj.sublime: '>=1.0.0'
  makinj.docker: '>=1.0.0'
  makinj.gcloud: '>=1.0.0'
  makinj.kubectl: '>=1.0.0'
  makinj.golang: '>=1.0.0'
  makinj.kind: '>=1.0.0'
  makinj.autochrome: '>=1.0.0'
  makinj.mitmproxy: '>=1.0.0'
  # makinj.kali: '>=1.0.0'
  # makinj.aws: '>=1.0.0'
  # makinj.configs: '>=1.0.0'
  # makinj.ethereum: '>=1.0.0'
  # makinj.samba: '>=1.0.0'
  # makinj.scoutsuite: '>=1.0.0'
  # makinj.terraform: '>=1.0.0'
  # makinj.packer: '>=1.0.0'
  # makinj.vagrant: '>=1.0.0'
  # makinj.vault: '>=1.0.0'
repository: https://github.com/vmutti/AnsibleCollections
issues: https://github.com/vmutti/AnsibleCollections/issues
build_ignore: []

