---
galaxy_info:
  author: Shoshana Makinen
  description: Creates local human user accounts with sudo access for each user in human_usernames

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
