---
galaxy_info:
  author: Shoshana Makinen
  description: Downloads and installs the Go toolchain system-wide, and updates each user's PATH in .zshrc

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
