- name: "Install libvirt if necessary"
  when: "'host_install_libvirt' in group_names"
  block:
    - name: Install packages
      become: true
      apt:
        update_cache: true
        pkg: "{{ libvirt_packages }}"

    - name: Enable and start libvirtd
      become: true
      systemd:
        name: libvirtd
        enabled: true
        state: started

    - name: "Add {{ libvirt_usernames }} to libvirt/kvm groups"
      become: true
      user:
        name: "{{ libvirt_username }}"
        append: yes
        groups:
          - libvirt
          - kvm
      with_items: "{{ libvirt_usernames }}"
      loop_control:
        loop_var: libvirt_username

    - name: Allow libvirt group members to manage libvirt without polkit authentication
      become: true
      copy:
        dest: /etc/polkit-1/rules.d/50-libvirt-group.rules
        mode: "0644"
        content: |
          polkit.addRule(function(action, subject) {
              if (action.id.indexOf("org.libvirt.") === 0 && subject.isInGroup("libvirt")) {
                  return polkit.Result.YES;
              }
          });
