---
galaxy_info:
  author: Shoshana Makinen
  description: Stops the Vault server and deletes its storage directory when vault_server_db_destroy_confirm is true

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
