---
galaxy_info:
  author: Shoshana Makinen
  description: Installs zsh and Oh My Zsh, restoring per-user .zshrc configuration and setting zsh as the user's shell

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
