---
galaxy_info:
  author: Shoshana Makinen
  description: Adds Sublime Text's apt repository, installs sublime-text, and restores per-user configuration

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
