---
galaxy_info:
  author: Shoshana Makinen
  description: Adds the Kubernetes apt repository/keyring for kubectl_version and installs kubectl

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
