---
galaxy_info:
  author: Shoshana Makinen
  description: Adds each user in virtualbox_sf_usernames to the vboxsf group for VirtualBox shared folder access

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
