---
galaxy_info:
  author: Shoshana Makinen
  description: Installs vim and git, restoring per-user configuration for each user in vim_usernames

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
