---
galaxy_info:
  author: Shoshana Makinen
  description: Adds the Kali Linux apt repository/keyring and installs the configured list of kali_packages

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
