- hosts: vault_hypervisor
  vars:
    vault_server_db_destroy_confirm: true
  roles:
    - vmutti.vault.server_db_destroy
    - vmutti.vault.server_tls_disable
- hosts: vault_server
  roles:
    - vmutti.vault.server_db_create
    - vmutti.vault.server_db_unseal
    - vmutti.vault.server_db_deploy_admin_user
    - vmutti.vault.server_db_deploy_root_ca
    - vmutti.vault.server_db_deploy_int_ca
