- name: "Install Virtualbox guest additions if necessary"
  when: "'host_install_virtualbox_guest' in group_names"
  block:
    - name: "Installing dependencies for guest additions"
      become: true
      apt:
        update_cache: yes
        pkg:
          - virtualbox-guest-x11
