---
galaxy_info:
  author: Shoshana Makinen
  description: Downloads a random image from picsum.photos and installs it as the default desktop background

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
