---
galaxy_info:
  author: Shoshana Makinen
  description: Installs the Ansible Python package via pip when host_install_ansible is true

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
