---
galaxy_info:
  author: Shoshana Makinen
  description: Archives and fetches each configured service's user/system config paths from a host back to the controller

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
