---
galaxy_info:
  author: Shoshana Makinen
  description: Runs a full apt dist-upgrade with autoremove to keep the host's packages up to date

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
