---
galaxy_info:
  author: Shoshana Makinen
  description: Adds Google Cloud's apt repository and installs the google-cloud-sdk package

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
