# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'

require("json")
require("./guest.rb")


Vagrant.configure("2") do |vagrant|
  
  guest_configs=JSON.parse(File.open("./guests.json").read())

  guests=[]
  guest_configs.each { |guest_config|
    guests.push(Guest.new(vagrant, guest_config))
  }

end
 
