- name: Deploy libvirt storage pools
  include_tasks: pools.yml

- name: Configure AppArmor access for libvirt storage pools
  include_tasks: apparmor.yml

- name: Deploy libvirt networks
  include_tasks: networks.yml

- name: Deploy libvirt guest domains
  include_tasks: domains.yml
