---
galaxy_info:
  author: Shoshana Makinen
  description: Installs tmux and restores per-user configuration for each user in tmux_usernames

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
