- name: "Install golang if necessary ({{install_golang}})"
  when: "'host_install_golang' in group_names"
  block:
    - name: "Download golang binaries"
      unarchive:
        src: https://go.dev/dl/go{{golang_version}}.{{ansible_system | lower}}-{{golang_architecture_name_mapping[ansible_facts.userspace_architecture]}}.tar.gz
        dest: "{{golang_install_dir}}"
        remote_src: true
      become: true
    - name: "Update PATH for golang users"
      lineinfile:
        path: "/home/{{golang_username}}/.zshrc"
        line: "export PATH=$PATH:{{golang_install_dir}}/go/bin:$GOPATH/bin"
        search_string: "export PATH=$PATH:{{golang_install_dir}}/go/bin:$GOPATH/bin"
      with_items: "{{ golang_usernames }}"
      loop_control:
        loop_var: golang_username
      become: true
