- name: "Install fonts if necessary"
  when: "'host_install_fonts' in group_names"
  block:
    - name: "Configure each font"
      include_tasks: font.yml

      with_items: "{{ font_urls }}"
      loop_control:
        loop_var: font_url
