---
galaxy_info:
  author: Shoshana Makinen
  description: Manages a Podman container per guest host using that host's podman_* variables, via containers.podman

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
