- name: "Install zsh if necessary"
  when: "'host_install_zsh' in group_names"
  block:
  - name: "Installing git, zsh"
    become: true
    apt:
      update_cache: yes
      pkg:
        - zsh
        - git
  - name: "Installing fonts-powerline if debian"
    become: true
    apt:
      update_cache: yes
      pkg:
        - fonts-powerline
    when: "'debian' in group_names"

  - name: "get path for zsh"
    command: which zsh
    register: which_zsh_binary_path

  - name: "get path for zsh"
    set_fact: 
      zsh_binary_path: "{{which_zsh_binary_path.stdout}}"

  - name: Clone OhMyzsh
    git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: /tmp/ohmyzsh

  - name: "Configure Zsh for each user"
    include_tasks: configure_for_user.yml
    with_items: "{{ zsh_usernames }}"
    loop_control:
      loop_var: zsh_username
