---
galaxy_info:
  author: Shoshana Makinen
  description: Meta-role that includes a curated set of vmutti.* roles behind Ansible tags to provision a personal workstation

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
