---
galaxy_info:
  author: Shoshana Makinen
  description: Writes a Vagrant project and per-guest configs derived from inventory, then runs vagrant up for each guest

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
