- name: "Install kubectl if necessary "
  when: "'host_install_kubectl' in group_names"
  block:
    - name: Install GPG key for K8s SDK
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /etc/apt/keyrings/k8s.asc
        mode: '0644'
        force: true
      become: true

    - name: Add kubernetes repositories into sources list
      become: true
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/k8s.asc] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        state: present
        filename: kubernetes

    - name: Install kubectl package
      become: true
      apt:
        update_cache: true
        pkg: 
          - kubectl
