---
galaxy_info:
  author: Shoshana Makinen
  description: Downloads and installs a pinned version of the kind CLI binary

  license: MIT

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
